### PR TITLE
First upload to review

### PR DESCRIPTION
**Pull request by NitzanC07**
Hi, 
I know it is not perfect, and the sign-in and sign-up aren't working, but I sent it to get a review about the markup.
I'll try to understand how to implement the signing-in and signing-up at the continue.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for sending your project for review, good job. I left several comments below, you should fix them to pass this diploma stage. Good luck with the refactoring!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * The page looks incorrectly on 1440 viewport - the page has incorrect page width and width of several text elements in the page, incorrect spaces between the elements and sections, incorrect text properties for headings on the page, incorrect size of the `about__image`
    * Incorrect text properties of `popup__input` on 1440 viewport
    * You need to import all necessary font-faces for the project (note, that several text elements on the page have `900` and `500` font weight, so they need a separate font-face
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Incorrect height of the `header` on 768 and 320 viewport (please also check the size of the logo)
    * Incorrect width of `search-form__title` and `search-form__text` on 768 viewport
    * Incorrect width of `search-form__button` on 768 viewport
    * Please check all spaces between elements inside `search-form` block on 768 and 320 viewport
    * Incorrect bottom margin of `news-card-list__title` on 768 and 320 viewport
    * Incorrect number of cards per line in `news-card-list__cards` on 768 viewport
    * Footer looks incorrectly on 768 and on 320 viewport (please check the width of the section and width of all elements, their text properties and spaces between all elements)
    * Incorrect spaces between elements inside `header__menu` on 320 viewport
    * Incorrect width of `search-form__input` and `search-form__button` on 320 viewport
    * Incorrect width and height of `news-card` on 320 viewport
    * `header` isn't centered horizontally on 768 viewport http://joxi.ru/1A5E1PXu433XZA
    * Incorrect width of `saved-news-title` and spaces between elements inside the block on 768 and on 320 viewport
    * Incorrect height of the popup window on 768 viewport
    * Incorrect width of all content inside popup window on 320 viewport
    * Incorrect height of the popup window on 320 viewport http://joxi.ru/E2p7L4BsvQQPnm
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `news-card__save-button-icon` should have active state 
- [ ]  The design reuses components wherever possible.
    * header can be the same component on both pages
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * favicon should be a vector too
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Fallback fonts are added not to all of the font styles
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

**Comment by NitzanC07** [comment]
Hi, 
I fixed most of the comments, and I send it to another review.

**Comment by FiLLa-FaS** [comment]
Hey! Most of the issues were fixed, good job! But there're still several issues that should be fixed to pass the sprint. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * The page looks incorrectly on 1440 viewport - the page has incorrect page width and width of several text elements in the page, incorrect spaces between the elements and sections, incorrect text properties for headings on the page, incorrect size of the `about__image`. For example, take a look at header part http://joxi.ru/zAN74gas1GoDMr, we can see that final width of the section is bigger than it should be, because side spaces are much smaller than they should be on this screen resolution
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Incorrect height of the `header` on 768 viewport
    * Incorrect spaces between elements inside `header__menu` on 320 viewport http://joxi.ru/E2p7L4BsvE6R8m
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.
    * header can be the same component on both pages
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Fallback fonts are added not to all of the font styles
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 71

**Comment by NitzanC07** [comment]
I connected both headers that I made to one component with appropriate colors to each one with JSX. 
And I changed the SavedNewsTitle to SavedNewsHeader, because now I understood I made wrong. 
And I added all the alternatives fonts to all fonts at every component that contain fonts.

**Comment by FiLLa-FaS** [comment]
Hey! Your project is almost finished, only two small issues are left. Note, that the next iteration will be the last, please check your project before submitting and make sure that at least one of the issues is fixed correctly. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect width of the `footer` on 1440px
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Incorrect spaces between elements inside header__menu on 320 viewport (now final height of the header + menu is 231px and should be 286px http://joxi.ru/VrwGn4bsoLQO3r. Please check all spaces
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by NitzanC07** [comment]
Hi,
I fixed the resolution in the Footer.
In the header__menu, I fixed it, but it is not exactly 286px (with the header itself), because I don't understand how to do it exactly like the Figma.

**Comment by FiLLa-FaS** [comment]
Hey! You've fixed all the issues, so now your project is accepted. Good luck on the next diploma stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Comment by NitzanC07** [comment]
Thank you!

**Pull request merged**
